export const characters = [
    {
        id: 1,
        qty: 1,
        name: 'Aryte',
        gender: 'Male',
        race: 'Human',
        class: 'Paladin',
        age: 37,
        height: `5'9''`,
        description: 'Man standing with sword',
        Strength: 'Can take a beating',
        Weakness: 'Interacting with people',
        price: 8,
        img: 'paladin.jpeg'
    },
    {
        id: 2,
        qty: 1,
        name: 'Esvele Tallstag',
        gender: 'Female',
        race: 'Human',
        class: 'Rogue',
        age: 18,
        height: `5'4''`,
        description: 'Woman standing with dagger',
        Strength: 'Very Strong',
        Weakness: 'Not very wise',
        price: 5,
        img: 'rogue.jpg'
    },
    {
        id: 3,
        qty: 1,
        name: 'Ander Leagallow',
        gender: 'Male',
        race: 'Human',
        class: 'Sorcerer',
        age: 56,
        height: `5'10''`,
        description: 'Old Man creating fireball',
        Strength: 'Extremely wise',
        Weakness: 'Very weak',
        price: 14,
        img: 'sorcerer.jpeg'
    },
    {
        id: 4,
        qty: 1,
        name: 'Darastrix',
        gender: 'Male',
        race: 'Human',
        class: 'Fighter',
        age: 67,
        height: `6'3''`,
        description: 'Old man in suit of armor',
        Strength: 'A born leader',
        Weakness: 'Not as fast as he once was',
        price: 10,
        img: 'fighter.jpeg'
    },
    {
        id: 5,
        qty: 1,
        name: 'Caelynn Horineth',
        gender: 'Female',
        race: 'Elf',
        class: 'Ranger',
        age: 371,
        height: `5'3''`,
        description: 'Woman drawing her bow',
        Strength: 'Very perceptive',
        Weakness: 'Quick to anger',
        price: 9,
        img: 'ranger.jpeg'
    },
    {
        id: 6,
        qty: 1,
        name: 'Quespa Turnuroth',
        gender: 'Female',
        race: 'Dragonborn',
        class: 'Warlock',
        age: 43,
        height: `6'1''`,
        description: 'Dragon zapping their sword',
        Strength: 'Highly intellectual',
        Weakness: 'Not very charismatic',
        price: 9,
        img: 'warlock.jpeg'
    }
]